apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpersistentvolume
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
    type: DirectoryOrCreate
    
