apiVersion: apps/v1
kind: Deployment
metadata: 
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata: 
      labels:
        app : users
    spec:
      containers:
        - name: users
          image: snadi043/docker_kubernetes_networking_users_api:latest
          env:
            - name: AUTH_ADDRESS
              # value: "10.104.213.243"
              value: "auth-service.default"
  